/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3d-model/flower_sanguinaria_canadensis.glb --output components/models/FlowerSanguinariaCanadensis.tsx --types --keepnames --shadows 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Flower_Sanguinaria_canadensis1_Material_#0_0']: THREE.Mesh
    ['Flower_Sanguinaria_canadensis2_Material_#1_0']: THREE.Mesh
    ['Flower_Sanguinaria_canadensis3_Material_#2_0']: THREE.Mesh
    ['Flower_Sanguinaria_canadensis4_Material_#3_0']: THREE.Mesh
    ['Flower_Sanguinaria_canadensis5_Material_#4_0']: THREE.Mesh
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
    Material_1: THREE.MeshStandardMaterial
    Material_2: THREE.MeshStandardMaterial
    Material_3: THREE.MeshStandardMaterial
    Material_4: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/flower_sanguinaria_canadensis.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Flower_Sanguinaria_canadensis1_Material_#0_0" castShadow receiveShadow geometry={nodes['Flower_Sanguinaria_canadensis1_Material_#0_0'].geometry} material={materials.Material_0} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Flower_Sanguinaria_canadensis2_Material_#1_0" castShadow receiveShadow geometry={nodes['Flower_Sanguinaria_canadensis2_Material_#1_0'].geometry} material={materials.Material_1} position={[143.712, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Flower_Sanguinaria_canadensis3_Material_#2_0" castShadow receiveShadow geometry={nodes['Flower_Sanguinaria_canadensis3_Material_#2_0'].geometry} material={materials.Material_2} position={[143.712, 0, 223.877]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Flower_Sanguinaria_canadensis4_Material_#3_0" castShadow receiveShadow geometry={nodes['Flower_Sanguinaria_canadensis4_Material_#3_0'].geometry} material={materials.Material_3} position={[-18.185, 0, 223.877]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Flower_Sanguinaria_canadensis5_Material_#4_0" castShadow receiveShadow geometry={nodes['Flower_Sanguinaria_canadensis5_Material_#4_0'].geometry} material={materials.Material_4} position={[74.305, 0, 108.04]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/flower_sanguinaria_canadensis.glb')
